Update application.js
`setCookie("timezone", timezone.name())` returns an error `Uncaught TypeError: findTimeZone(...).name is not a function` because `findTimeZone()` already returns `name()`